# Generated by Django 4.2.6 on 2024-08-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_category_datetime_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
