# Generated by Django 4.2.6 on 2024-08-20 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_address_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_detail',
        ),
    ]
